export const contentData = {
    'Básico': [
        // Numbers
        { id: 1, english: 'One', phonetic: 'Uãn', translation: 'Um' },
        { id: 2, english: 'Two', phonetic: 'Tú', translation: 'Dois' },
        { id: 3, english: 'Three', phonetic: 'Trí', translation: 'Três' },
        { id: 4, english: 'Four', phonetic: 'Fór', translation: 'Quatro' },
        { id: 5, english: 'Five', phonetic: 'Fáiv', translation: 'Cinco' },
        { id: 6, english: 'Six', phonetic: 'Sícs', translation: 'Seis' },
        { id: 7, english: 'Seven', phonetic: 'Sévem', translation: 'Sete' },
        { id: 8, english: 'Eight', phonetic: 'Êit', translation: 'Oito' },
        { id: 9, english: 'Nine', phonetic: 'Náin', translation: 'Nove' },
        { id: 10, english: 'Ten', phonetic: 'Tén', translation: 'Dez' },
        // Colors
        { id: 11, english: 'Red', phonetic: 'Réd', translation: 'Vermelho' },
        { id: 12, english: 'Blue', phonetic: 'Blú', translation: 'Azul' },
        { id: 13, english: 'Green', phonetic: 'Grín', translation: 'Verde' },
        { id: 14, english: 'Yellow', phonetic: 'Ié-lou', translation: 'Amarelo' },
        { id: 15, english: 'Black', phonetic: 'Bléc', translation: 'Preto' },
        { id: 16, english: 'White', phonetic: 'Uáit', translation: 'Branco' },
        { id: 17, english: 'Orange', phonetic: 'Ó-rendj', translation: 'Laranja' },
        { id: 18, english: 'Pink', phonetic: 'Pínc', translation: 'Rosa' },
        { id: 19, english: 'Purple', phonetic: 'Pãr-pôu', translation: 'Roxo' },
        { id: 20, english: 'Brown', phonetic: 'Bráun', translation: 'Marrom' },
        // Family
        { id: 21, english: 'Father', phonetic: 'Fá-dêr', translation: 'Pai' },
        { id: 22, english: 'Mother', phonetic: 'Mã-dêr', translation: 'Mãe' },
        { id: 23, english: 'Brother', phonetic: 'Brã-dêr', translation: 'Irmão' },
        { id: 24, english: 'Sister', phonetic: 'Sís-têr', translation: 'Irmã' },
        { id: 25, english: 'Son', phonetic: 'Sãn', translation: 'Filho' },
        { id: 26, english: 'Daughter', phonetic: 'Dó-têr', translation: 'Filha' },
        { id: 27, english: 'Baby', phonetic: 'Bêi-bi', translation: 'Bebê' },
        { id: 28, english: 'Grandpa', phonetic: 'Grénd-pa', translation: 'Vovô' },
        { id: 29, english: 'Grandma', phonetic: 'Grénd-ma', translation: 'Vovó' },
        { id: 30, english: 'Uncle', phonetic: 'Ãn-côu', translation: 'Tio' },
        // Animals
        { id: 31, english: 'Dog', phonetic: 'Dóg', translation: 'Cachorro' },
        { id: 32, english: 'Cat', phonetic: 'Quét', translation: 'Gato' },
        { id: 33, english: 'Bird', phonetic: 'Bãrd', translation: 'Pássaro' },
        { id: 34, english: 'Fish', phonetic: 'Físh', translation: 'Peixe' },
        { id: 35, english: 'Horse', phonetic: 'Rórs', translation: 'Cavalo' },
        { id: 36, english: 'Cow', phonetic: 'Cáu', translation: 'Vaca' },
        { id: 37, english: 'Pig', phonetic: 'Píg', translation: 'Porco' },
        { id: 38, english: 'Lion', phonetic: 'Láion', translation: 'Leão' },
        { id: 39, english: 'Tiger', phonetic: 'Tái-guêr', translation: 'Tigre' },
        { id: 40, english: 'Bear', phonetic: 'Bér', translation: 'Urso' },
        // Food & Drink
        { id: 41, english: 'Apple', phonetic: 'É-pou', translation: 'Maçã' },
        { id: 42, english: 'Banana', phonetic: 'Ba-né-na', translation: 'Banana' },
        { id: 43, english: 'Milk', phonetic: 'Míulc', translation: 'Leite' },
        { id: 44, english: 'Water', phonetic: 'Uóter', translation: 'Água' },
        { id: 45, english: 'Bread', phonetic: 'Bréd', translation: 'Pão' },
        { id: 46, english: 'Meat', phonetic: 'Mit', translation: 'Carne' },
        { id: 47, english: 'Chicken', phonetic: 'Tchíquim', translation: 'Frango' },
        { id: 48, english: 'Egg', phonetic: 'Égu', translation: 'Ovo' },
        { id: 49, english: 'Rice', phonetic: 'Ráis', translation: 'Arroz' },
        { id: 50, english: 'Bean', phonetic: 'Bín', translation: 'Feijão' },
        // Objects
        { id: 51, english: 'Table', phonetic: 'Têi-bou', translation: 'Mesa' },
        { id: 52, english: 'Chair', phonetic: 'Tchér', translation: 'Cadeira' },
        { id: 53, english: 'Bed', phonetic: 'Béd', translation: 'Cama' },
        { id: 54, english: 'Door', phonetic: 'Dór', translation: 'Porta' },
        { id: 55, english: 'Window', phonetic: 'Uín-dou', translation: 'Janela' },
        { id: 56, english: 'Car', phonetic: 'Cár', translation: 'Carro' },
        { id: 57, english: 'Bus', phonetic: 'Bãs', translation: 'Ônibus' },
        { id: 58, english: 'House', phonetic: 'Ráus', translation: 'Casa' },
        { id: 59, english: 'Book', phonetic: 'Buc', translation: 'Livro' },
        { id: 60, english: 'Pen', phonetic: 'Pén', translation: 'Caneta' },
        // Body Parts
        { id: 61, english: 'Head', phonetic: 'Réd', translation: 'Cabeça' },
        { id: 62, english: 'Eye', phonetic: 'Ái', translation: 'Olho' },
        { id: 63, english: 'Nose', phonetic: 'Nôuz', translation: 'Nariz' },
        { id: 64, english: 'Mouth', phonetic: 'Máut', translation: 'Boca' },
        { id: 65, english: 'Ear', phonetic: 'Iír', translation: 'Orelha' },
        { id: 161, english: 'Hand', phonetic: 'Rénd', translation: 'Mão' },
        { id: 67, english: 'Foot', phonetic: 'Fút', translation: 'Pé' },
        { id: 162, english: 'Leg', phonetic: 'Légu', translation: 'Perna' },
        { id: 163, english: 'Arm', phonetic: 'Árm', translation: 'Braço' },
        { id: 70, english: 'Hair', phonetic: 'Rér', translation: 'Cabelo' },
        { id: 164, english: 'Wait', phonetic: 'Uêit', translation: 'Espere' },
        { id: 165, english: 'Call', phonetic: 'Cól', translation: 'Chamar/Ligar' },
        { id: 166, english: 'Ask', phonetic: 'Ésc', translation: 'Perguntar' },
        { id: 167, english: 'Hear', phonetic: 'Rí-êr', translation: 'Ouvir' },
        { id: 168, english: 'Feel', phonetic: 'Fí-sh', translation: 'Sentir' },
        { id: 169, english: 'Keep', phonetic: 'Quíp', translation: 'Manter' },
        { id: 170, english: 'Try', phonetic: 'Trái', translation: 'Tentar' },
        { id: 171, english: 'Work', phonetic: 'Uãrk', translation: 'Trabalho' },
        { id: 172, english: 'Study', phonetic: 'Is-tã-dy', translation: 'Estudar' },
        { id: 173, english: 'Learn', phonetic: 'Lãrn', translation: 'Aprender' },
        { id: 174, english: 'Teach', phonetic: 'Títch', translation: 'Ensinar' },
        { id: 175, english: 'Drive', phonetic: 'Dráiv', translation: 'Dirigir' },
        { id: 176, english: 'Walk', phonetic: 'Uól-sh', translation: 'Caminhar' },
        { id: 177, english: 'Run', phonetic: 'Rãn', translation: 'Correr' },
        { id: 178, english: 'Jump', phonetic: 'Djãmp', translation: 'Pular' },
        { id: 179, english: 'Sing', phonetic: 'Síng', translation: 'Cantar' },
        { id: 180, english: 'Dance', phonetic: 'Dénce', translation: 'Dançar' },
        // Family
        { id: 181, english: 'Father', phonetic: 'Fá-dhêr', translation: 'Pai' },
        { id: 182, english: 'Mother', phonetic: 'Má-dhêr', translation: 'Mãe' },
        { id: 183, english: 'Son', phonetic: 'Sãn', translation: 'Filho' },
        { id: 184, english: 'Daughter', phonetic: 'Dó-têr', translation: 'Filha' },
        { id: 185, english: 'Brother', phonetic: 'Brá-dhêr', translation: 'Irmão' },
        { id: 186, english: 'Sister', phonetic: 'Sís-têr', translation: 'Irmã' },
        { id: 187, english: 'Grandfather', phonetic: 'Grénd-fá-dhêr', translation: 'Avô' },
        { id: 188, english: ' grandmother', phonetic: 'Grénd-má-dhêr', translation: 'Avó' },
        { id: 189, english: 'Uncle', phonetic: 'Ãn-cl', translation: 'Tio' },
        { id: 190, english: 'Aunt', phonetic: 'Ént', translation: 'Tia' },
        // Colors
        { id: 191, english: 'Black', phonetic: 'Bléc', translation: 'Preto' },
        { id: 192, english: 'White', phonetic: 'Uáit', translation: 'Branco' },
        { id: 193, english: 'Red', phonetic: 'Réd', translation: 'Vermelho' },
        { id: 194, english: 'Blue', phonetic: 'Blú', translation: 'Azul' },
        { id: 195, english: 'Green', phonetic: 'Grín', translation: 'Verde' },
        { id: 196, english: 'Yellow', phonetic: 'Ié-lôu', translation: 'Amarelo' },
        { id: 197, english: 'Orange', phonetic: 'Ó-réndj', translation: 'Laranja' },
        { id: 198, english: 'Pink', phonetic: 'Pínc', translation: 'Rosa' },
        { id: 199, english: 'Brown', phonetic: 'Bráun', translation: 'Marrom' },
        { id: 200, english: 'Gray', phonetic: 'Grêi', translation: 'Cinza' },
        // More Numbers
        { id: 201, english: 'Eleven', phonetic: 'I-lé-vên', translation: 'Onze' },
        { id: 202, english: 'Twelve', phonetic: 'Tuél-v', translation: 'Doze' },
        { id: 203, english: 'Thirteen', phonetic: 'Thãr-tín', translation: 'Treze' },
        { id: 204, english: 'Fourteen', phonetic: 'Fór-tín', translation: 'Quatorze' },
        { id: 205, english: 'Fifteen', phonetic: 'Fíf-tín', translation: 'Quinze' },
        { id: 206, english: 'Twenty', phonetic: 'Tuên-ti', translation: 'Vinte' },
        { id: 207, english: 'Thirty', phonetic: 'Thãr-ti', translation: 'Trinta' },
        { id: 208, english: 'Forty', phonetic: 'Fór-ti', translation: 'Quarenta' },
        { id: 209, english: 'Fifty', phonetic: 'Fíf-ti', translation: 'Cinquenta' },
        { id: 210, english: 'One hundred', phonetic: 'Uãn rãn-drêd', translation: 'Cem' },
        // House Objects
        { id: 211, english: 'Door', phonetic: 'Dór', translation: 'Porta' },
        { id: 212, english: 'Window', phonetic: 'Uín-dou', translation: 'Janela' },
        { id: 213, english: 'Table', phonetic: 'Têi-bl', translation: 'Mesa' },
        { id: 214, english: 'Chair', phonetic: 'Tchér', translation: 'Cadeira' },
        { id: 215, english: 'Bed', phonetic: 'Béd', translation: 'Cama' },
        { id: 216, english: 'Key', phonetic: 'Quí', translation: 'Chave' },
        { id: 217, english: 'Towel', phonetic: 'Táu-sh', translation: 'Toalha' },
        { id: 218, english: 'Soap', phonetic: 'Sôup', translation: 'Sabão' },
        { id: 219, english: 'Kitchen', phonetic: 'Quí-tshên', translation: 'Cozinha' },
        { id: 220, english: 'Bathroom', phonetic: 'Béth-rúm', translation: 'Banheiro' },
        // Animals
        { id: 221, english: 'Dog', phonetic: 'Dóg', translation: 'Cachorro' },
        { id: 222, english: 'Cat', phonetic: 'Quét', translation: 'Gato' },
        { id: 223, english: 'Bird', phonetic: 'Bãrd', translation: 'Pássaro' },
        { id: 224, english: 'Horse', phonetic: 'Rórs', translation: 'Cavalo' },
        { id: 225, english: 'Cow', phonetic: 'Cáu', translation: 'Vaca' },
        { id: 226, english: 'Pig', phonetic: 'Pígui', translation: 'Porco' },
        { id: 227, english: 'Chicken', phonetic: 'Tchí-quên', translation: 'Frango/Galinha' },
        { id: 228, english: 'Lion', phonetic: 'Lái-ôn', translation: 'Leão' },
        { id: 229, english: 'Tiger', phonetic: 'Tái-guêr', translation: 'Tigre' },
        { id: 230, english: 'Elephant', phonetic: 'É-li-fênt', translation: 'Elefante' },
        // Clothing
        { id: 231, english: 'Shirt', phonetic: 'Shãrt', translation: 'Camisa' },
        { id: 232, english: 'Pants', phonetic: 'Pénts', translation: 'Calças' },
        { id: 233, english: 'Shoes', phonetic: 'Shús', translation: 'Sapatos' },
        { id: 234, english: 'Socks', phonetic: 'Sócs', translation: 'Meias' },
        { id: 235, english: 'Hat', phonetic: 'Rét', translation: 'Chapéu' },
        { id: 236, english: 'Dress', phonetic: 'Dréss', translation: 'Vestido' },
        { id: 237, english: 'Skirt', phonetic: 'I-squãrt', translation: 'Saia' },
        { id: 238, english: 'Coat', phonetic: 'Côut', translation: 'Casaco' },
        { id: 239, english: 'Watch', phonetic: 'Uátch', translation: 'Relógio' },
        { id: 240, english: 'Glasses', phonetic: 'Glé-ssêz', translation: 'Óculos' },
        // Kitchen/Food Objects
        { id: 241, english: 'Plate', phonetic: 'Plêit', translation: 'Prato' },
        { id: 242, english: 'Glass', phonetic: 'Gléss', translation: 'Copo/Vidro' },
        { id: 243, english: 'Fork', phonetic: 'Fórc', translation: 'Garfo' },
        { id: 244, english: 'Knife', phonetic: 'Náif', translation: 'Faca' },
        { id: 245, english: 'Spoon', phonetic: 'I-spún', translation: 'Colher' },
        { id: 246, english: 'Bottle', phonetic: 'Bó-tl', translation: 'Garrafa' },
        { id: 247, english: 'Cup', phonetic: 'Cãp', translation: 'Xícara' },
        { id: 248, english: 'Bowl', phonetic: 'Bôu-l', translation: 'Tigela' },
        { id: 249, english: 'Pan', phonetic: 'Pén', translation: 'Panela' },
        { id: 250, english: 'Fridge', phonetic: 'Frídj', translation: 'Geladeira' },
        // Health/Body
        { id: 251, english: 'Doctor', phonetic: 'Dóc-tôr', translation: 'Médico' },
        { id: 252, english: 'Nurse', phonetic: 'Nãrs', translation: 'Enfermeiro' },
        { id: 253, english: 'Hospital', phonetic: 'Rós-pi-tl', translation: 'Hospital' },
        { id: 254, english: 'Medicine', phonetic: 'Mé-di-cin', translation: 'Remédio' },
        { id: 255, english: 'Pain', phonetic: 'Pêin', translation: 'Dor' },
        { id: 256, english: 'Sick', phonetic: 'Síc', translation: 'Doente' },
        { id: 257, english: 'Healthy', phonetic: 'Rél-thi', translation: 'Saudável' },
        { id: 258, english: 'Strong', phonetic: 'I-istróng', translation: 'Forte' },
        { id: 259, english: 'Weak', phonetic: 'Uíc', translation: 'Fraco' },
        { id: 260, english: 'Blood', phonetic: 'Blãd', translation: 'Sangue' },
        // Emotions
        { id: 261, english: 'Angry', phonetic: 'Éng-gri', translation: 'Bravo' },
        { id: 262, english: 'Surprised', phonetic: 'Sãr-prái-zd', translation: 'Surpreso' },
        { id: 263, english: 'Bored', phonetic: 'Bórd', translation: 'Entediado' },
        { id: 264, english: 'Tired', phonetic: 'Tái-êrd', translation: 'Cansado' },
        { id: 265, english: 'Hungry', phonetic: 'Rãng-gri', translation: 'Faminto' },
        { id: 266, english: 'Thirsty', phonetic: 'Thãrs-ti', translation: 'Sedento' },
        { id: 267, english: 'Excited', phonetic: 'É-csái-têd', translation: 'Animado' },
        { id: 268, english: 'Scared', phonetic: 'I-squérd', translation: 'Assustado' },
        { id: 269, english: 'Proud', phonetic: 'Práud', translation: 'Orgulhoso' },
        { id: 270, english: 'Calm', phonetic: 'Cálm', translation: 'Calmo' },
        // Adjectives
        { id: 71, english: 'Happy', phonetic: 'Ré-pi', translation: 'Feliz' },
        { id: 72, english: 'Sad', phonetic: 'Séd', translation: 'Triste' },
        { id: 73, english: 'Angry', phonetic: 'Éngri', translation: 'Bravo' },
        { id: 74, english: 'Sleepy', phonetic: 'Slí-pi', translation: 'Com sono' },
        { id: 75, english: 'Hungry', phonetic: 'Rãngri', translation: 'Com fome' },
        { id: 76, english: 'Big', phonetic: 'Bíg', translation: 'Grande' },
        { id: 77, english: 'Small', phonetic: 'Ismól', translation: 'Pequeno' },
        { id: 78, english: 'Hot', phonetic: 'Rót', translation: 'Quente' },
        { id: 79, english: 'Cold', phonetic: 'Côuld', translation: 'Frio' },
        { id: 80, english: 'Fast', phonetic: 'Fést', translation: 'Rápido' },
        // More basic nouns
        { id: 81, english: 'Sky', phonetic: 'Scái', translation: 'Céu' },
        { id: 82, english: 'Sun', phonetic: 'Sãn', translation: 'Sol' },
        { id: 83, english: 'Moon', phonetic: 'Mûn', translation: 'Lua' },
        { id: 84, english: 'Star', phonetic: 'Istár', translation: 'Estrela' },
        { id: 85, english: 'Rain', phonetic: 'Rêin', translation: 'Chuva' },
        { id: 86, english: 'Tree', phonetic: 'Trí', translation: 'Árvore' },
        { id: 87, english: 'Flower', phonetic: 'Fláu-êr', translation: 'Flor' },
        { id: 88, english: 'Mountain', phonetic: 'Máun-tên', translation: 'Montanha' },
        { id: 89, english: 'Beach', phonetic: 'Bítch', translation: 'Praia' },
        { id: 90, english: 'Ball', phonetic: 'Ból', translation: 'Bola' },
        // Essentials
        { id: 91, english: 'Yes', phonetic: 'Iés', translation: 'Sim' },
        { id: 92, english: 'No', phonetic: 'Nôu', translation: 'Não' },
        { id: 93, english: 'Hello', phonetic: 'Rêlou', translation: 'Olá' },
        { id: 94, english: 'Bye', phonetic: 'Bái', translation: 'Tchau' },
        { id: 95, english: 'Please', phonetic: 'Plís', translation: 'Por favor' },
        { id: 96, english: 'Thanks', phonetic: 'Téncs', translation: 'Obrigado' },
        { id: 97, english: 'Wait', phonetic: 'Uêit', translation: 'Espere' },
        { id: 98, english: 'Go', phonetic: 'Góu', translation: 'Ir' },
        { id: 99, english: 'Stop', phonetic: 'Istóp', translation: 'Parar' },
        { id: 100, english: 'Run', phonetic: 'Rãn', translation: 'Correr' },
        // ... adding more to reach hundreds
        { id: 101, english: 'Cup', phonetic: 'Cãp', translation: 'Xícara' },
        { id: 102, english: 'Bottle', phonetic: 'Bó-tou', translation: 'Garrafa' },
        { id: 103, english: 'Plate', phonetic: 'Plêit', translation: 'Prato' },
        { id: 104, english: 'Fork', phonetic: 'Fórc', translation: 'Garfo' },
        { id: 105, english: 'Knife', phonetic: 'Náif', translation: 'Faca' },
        { id: 106, english: 'Spoon', phonetic: 'Spûn', translation: 'Colher' },
        { id: 107, english: 'Glass', phonetic: 'Gléss', translation: 'Copo' },
        { id: 108, english: 'Napkin', phonetic: 'Nép-quin', translation: 'Guardanapo' },
        { id: 109, english: 'Salt', phonetic: 'Sólt', translation: 'Sal' },
        { id: 110, english: 'Pepper', phonetic: 'Pé-pêr', translation: 'Pimenta' },
        { id: 111, english: 'Coffee', phonetic: 'Có-fi', translation: 'Café' },
        { id: 112, english: 'Tea', phonetic: 'Ti', translation: 'Chá' },
        { id: 113, english: 'Sugar', phonetic: 'Shú-gar', translation: 'Açúcar' },
        { id: 114, english: 'Honey', phonetic: 'Rã-ni', translation: 'Mel' },
        { id: 115, english: 'Juice', phonetic: 'Djúce', translation: 'Suco' },
        { id: 116, english: 'Lemon', phonetic: 'Lé-mon', translation: 'Limão' },
        { id: 117, english: 'Cake', phonetic: 'Quêic', translation: 'Bolo' },
        { id: 118, english: 'Ice cream', phonetic: 'Áice crím', translation: 'Sorvete' },
        { id: 119, english: 'Cookie', phonetic: 'Cú-qui', translation: 'Biscoito' },
        { id: 120, english: 'Pasta', phonetic: 'Pés-ta', translation: 'Macarrão' },
        { id: 121, english: 'Pizza', phonetic: 'Pí-tzâ', translation: 'Pizza' },
        { id: 122, english: 'Salad', phonetic: 'Sé-lad', translation: 'Salada' },
        { id: 123, english: 'Soup', phonetic: 'Súp', translation: 'Sopa' },
        { id: 124, english: 'Sandwich', phonetic: 'Sénd-uitch', translation: 'Sanduíche' },
        { id: 125, english: 'Fruit', phonetic: 'Frút', translation: 'Fruta' },
        { id: 126, english: 'Vegetable', phonetic: 'Véd-jté-bou', translation: 'Vegetal' },
        { id: 127, english: 'Tomato', phonetic: 'To-mêi-tou', translation: 'Tomate' },
        { id: 128, english: 'Potato', phonetic: 'Po-têi-tou', translation: 'Batata' },
        { id: 129, english: 'Onion', phonetic: 'Ã-nion', translation: 'Cebola' },
        { id: 130, english: 'Garlic', phonetic: 'Gár-lic', translation: 'Alho' },
        { id: 131, english: 'Rice', phonetic: 'Ráis', translation: 'Arroz' },
        { id: 132, english: 'Bean', phonetic: 'Bín', translation: 'Feijão' },
        { id: 133, english: 'Corn', phonetic: 'Córn', translation: 'Milho' },
        { id: 134, english: 'Carrot', phonetic: 'Quéroti', translation: 'Cenoura' },
        { id: 135, english: 'Soap', phonetic: 'Sôup', translation: 'Sabonete' },
        { id: 136, english: 'Towel', phonetic: 'Táu-sh', translation: 'Toalha' },
        { id: 137, english: 'Paper', phonetic: 'Pêi-pêr', translation: 'Papel' },
        { id: 138, english: 'Money', phonetic: 'Mã-ni', translation: 'Dinheiro' },
        { id: 139, english: 'Bag', phonetic: 'Bégu', translation: 'Bolsa/Sacola' },
        { id: 140, english: 'Hat', phonetic: 'Rét', translation: 'Chapéu' },
        { id: 141, english: 'Shirt', phonetic: 'Shãrt', translation: 'Camisa' },
        { id: 142, english: 'Shoes', phonetic: 'Shûz', translation: 'Sapatos' },
        { id: 143, english: 'Clock', phonetic: 'Clóc', translation: 'Relógio' },
        { id: 144, english: 'Phone', phonetic: 'Fôun', translation: 'Telefone' },
        { id: 145, english: 'Street', phonetic: 'Strít', translation: 'Rua' },
        { id: 146, english: 'City', phonetic: 'Sí-ti', translation: 'Cidade' },
        { id: 147, english: 'World', phonetic: 'Uãr-shd', translation: 'Mundo' },
        { id: 148, english: 'Dream', phonetic: 'Drím', translation: 'Sonho' },
        { id: 149, english: 'Love', phonetic: 'Lãv', translation: 'Amor' },
        { id: 150, english: 'Peace', phonetic: 'Píce', translation: 'Paz' },
        { id: 151, english: 'Life', phonetic: 'Láif', translation: 'Vida' },
        { id: 152, english: 'Day', phonetic: 'Dêi', translation: 'Dia' },
        { id: 153, english: 'Night', phonetic: 'Náit', translation: 'Noite' },
        { id: 154, english: 'Morning', phonetic: 'Mór-ning', translation: 'Manhã' },
        { id: 155, english: 'Sun', phonetic: 'Sãn', translation: 'Sol' },
        { id: 156, english: 'Air', phonetic: 'Ér', translation: 'Ar' },
        { id: 157, english: 'Fire', phonetic: 'Fá-iêr', translation: 'Fogo' },
        { id: 158, english: 'Soul', phonetic: 'Sôu', translation: 'Alma' },
        { id: 159, english: 'Mind', phonetic: 'Máind', translation: 'Mente' },
        { id: 160, english: 'Body', phonetic: 'Bó-di', translation: 'Corpo' },
    ],
    'Médio': [
        { id: 1001, english: 'Good morning', phonetic: 'Gud mórning', translation: 'Bom dia' },
        { id: 1002, english: 'Good afternoon', phonetic: 'Gud éfter-nun', translation: 'Boa tarde' },
        { id: 1003, english: 'Good evening', phonetic: 'Gud ív-ning', translation: 'Boa noite (chegada)' },
        { id: 1004, english: 'Good night', phonetic: 'Gud náit', translation: 'Boa noite (saída)' },
        { id: 1005, english: 'How are you?', phonetic: 'Rau ár iú?', translation: 'Como vai você?' },
        { id: 1006, english: 'I am fine', phonetic: 'Ái ém fáin', translation: 'Estou bem' },
        { id: 1007, english: 'Nice to meet you', phonetic: 'Náis tu mit iú', translation: 'Prazer em te conhecer' },
        { id: 1008, english: 'What is your name?', phonetic: 'Uat is iór nêim?', translation: 'Qual é o seu nome?' },
        { id: 1009, english: 'My name is...', phonetic: 'Mái nêim is...', translation: 'Meu nome é...' },
        { id: 1010, english: 'Where are you from?', phonetic: 'Uér ár iú fróm?', translation: 'De onde você é?' },
        { id: 1011, english: 'I am from Brazil', phonetic: 'Ái ém fróm Bra-zíl', translation: 'Eu sou do Brasil' },
        { id: 1012, english: 'Thank you very much', phonetic: 'Ténc iú vé-ri mãtch', translation: 'Muito obrigado' },
        { id: 1013, english: 'You are welcome', phonetic: 'Iú ár uélcom', translation: 'De nada' },
        { id: 1014, english: 'Excuse me, please', phonetic: 'Équis-kiús mi, plís', translation: 'Com licença, por favor' },
        { id: 1015, english: 'I am sorry', phonetic: 'Ái ém sór-ri', translation: 'Sinto muito' },
        { id: 1016, english: 'Can you help me?', phonetic: 'Quen iú relp mi?', translation: 'Pode me ajudar?' },
        { id: 1017, english: 'Where is the bathroom?', phonetic: 'Uér is dâ bátrum?', translation: 'Onde fica o banheiro?' },
        { id: 1018, english: 'How much is it?', phonetic: 'Rau mãtch is it?', translation: 'Quanto custa isso?' },
        { id: 1019, english: 'What time is it?', phonetic: 'Uat táim is it?', translation: 'Que horas são?' },
        { id: 1020, english: 'I am hungry', phonetic: 'Ái ém rãngri', translation: 'Estou com fome' },
        { id: 1021, english: 'I am thirsty', phonetic: 'Ái ém térs-ti', translation: 'Estou com sede' },
        { id: 1022, english: 'I am tired', phonetic: 'Ái ém tái-êrd', translation: 'Estou cansado' },
        { id: 1023, english: 'Where do you live?', phonetic: 'Uér du iú lív?', translation: 'Onde você mora?' },
        { id: 1024, english: 'What do you do?', phonetic: 'Uat du iú dú?', translation: 'O que você faz?' },
        { id: 1025, english: 'I work at...', phonetic: 'Ái uãrk ét...', translation: 'Eu trabalho na...' },
        { id: 1026, english: 'I like music', phonetic: 'Ái láic miú-zic', translation: 'Gosto de música' },
        { id: 1027, english: 'Do you like coffee?', phonetic: 'Du iú láic có-fi?', translation: 'Você gosta de café?' },
        { id: 1028, english: 'Wait a minute', phonetic: 'Uêit ê mí-niti', translation: 'Espere um minuto' },
        { id: 1029, english: 'Everything is okay', phonetic: 'Évri-tíng is ôu-kêi', translation: 'Está tudo bem' },
        { id: 1030, english: 'See you later', phonetic: 'Sí iú lêiter', translation: 'Até mais tarde' },
        { id: 1031, english: 'See you tomorrow', phonetic: 'Sí iú tu-mó-rou', translation: 'Até amanhã' },
        { id: 1032, english: 'Have a nice day', phonetic: 'Rév ê náice dêi', translation: 'Tenha um bom dia' },
        { id: 1033, english: 'Call me later', phonetic: 'Cól mi lêi-têr', translation: 'Ligue-me mais tarde' },
        { id: 1034, english: 'I do not know', phonetic: 'Ái du nót nôu', translation: 'Eu não sei' },
        { id: 1035, english: 'I understand', phonetic: 'Ái andêrstend', translation: 'Eu entendo' },
        { id: 1036, english: 'I do not understand', phonetic: 'Ái du nót andêrstend', translation: 'Não entendo' },
        { id: 1037, english: 'Please repeat', phonetic: 'Plís ri-pít', translation: 'Por favor repita' },
        { id: 1038, english: 'Slow down, please', phonetic: 'Slôu dáun, plís', translation: 'Mais devagar, por favor' },
        { id: 1039, english: 'Help me here', phonetic: 'Relp mi rí-êr', translation: 'Ajude-me aqui' },
        { id: 1040, english: 'Where is the exit?', phonetic: 'Uér is dâ é-csit?', translation: 'Onde é a saída?' },
        { id: 1041, english: 'It is direct', phonetic: 'It is di-réct', translation: 'É direto' },
        { id: 1042, english: 'Turn here', phonetic: 'Tãrn rí-êr', translation: 'Vire aqui' },
        { id: 1043, english: 'Go straight', phonetic: 'Góu strêit', translation: 'Siga reto' },
        { id: 1044, english: 'Believe me', phonetic: 'Bi-lív mi', translation: 'Acredite em mim' },
        { id: 1045, english: 'Follow me', phonetic: 'Fó-lou mi', translation: 'Siga-me' },
        { id: 1046, english: 'Be careful', phonetic: 'Bi quér-ful', translation: 'Tome cuidado' },
        { id: 1047, english: 'Good luck', phonetic: 'Gud lăc', translation: 'Boa sorte' },
        { id: 1048, english: 'Just a moment', phonetic: 'Djãst ê môu-ment', translation: 'Só um momento' },
        { id: 1049, english: 'Never mind', phonetic: 'Né-vêr máind', translation: 'Esqueça/Deixa pra lá' },
        { id: 1050, english: 'I hope so', phonetic: 'Ái rôup sôu', translation: 'Espero que sim' },
        { id: 1051, english: 'I am so happy', phonetic: 'Ái ém sôu ré-pi', translation: 'Estou tão feliz' },
        { id: 1052, english: 'Wait for me', phonetic: 'Uêit fór mi', translation: 'Espere por mim' },
        { id: 1053, english: 'I forgot it', phonetic: 'Ái fór-gót it', translation: 'Eu esqueci' },
        { id: 1054, english: 'Where are we?', phonetic: 'Uér ár uí?', translation: 'Onde estamos?' },
        { id: 1055, english: 'Let’s go now', phonetic: 'Léts góu náu', translation: 'Vamos agora' },
        { id: 1056, english: 'I am not sure', phonetic: 'Ái ém nót shú-êr', translation: 'Não tenho certeza' },
        { id: 1057, english: 'It is too late', phonetic: 'It is tú lêit', translation: 'É muito tarde' },
        { id: 1058, english: 'Are you sure?', phonetic: 'Ár iú shú-êr?', translation: 'Você tem certeza?' },
        { id: 1059, english: 'What happened?', phonetic: 'Uat ré-pend?', translation: 'O que aconteceu?' },
        { id: 1060, english: 'I will call you', phonetic: 'Ái uíl cól iú', translation: 'Eu te ligo' },
        { id: 1061, english: 'Take your time', phonetic: 'Têic iór táim', translation: 'Leve o seu tempo' },
        { id: 1062, english: 'I’m on my way', phonetic: 'Áim ón mái uêi', translation: 'Estou a caminho' },
        { id: 1063, english: 'It looks good', phonetic: 'It lúcs gud', translation: 'Parece bom' },
        { id: 1064, english: 'I don’t mind', phonetic: 'Ái dôunt máind', translation: 'Eu não me importo' },
        { id: 1066, english: 'That’s enough', phonetic: 'Dhéts i-nãf', translation: 'Já chega/É o suficiente' },
        { id: 1067, english: 'It stays here', phonetic: 'It istêis rí-êr', translation: 'Fica aqui' },
        { id: 1068, english: 'I am arriving', phonetic: 'Ái ém a-rái-ving', translation: 'Estou chegando' },
        { id: 1069, english: 'Look at me', phonetic: 'Lúc ét mi', translation: 'Olhe para mim' },
        { id: 1070, english: 'Don’t worry', phonetic: 'Dôunt uã-ri', translation: 'Não se preocupe' },
        { id: 1071, english: 'It’s a secret', phonetic: 'Its ê sí-cret', translation: 'É um segredo' },
        { id: 1072, english: 'Tell me more', phonetic: 'Tél mi mór', translation: 'Me conte mais' },
        { id: 1073, english: 'I don’t know why', phonetic: 'Ái dôunt nôu uái', translation: 'Eu não sei por que' },
        { id: 1074, english: 'Where did you go?', phonetic: 'Uér díd iú góu?', translation: 'Aonde você foi?' },
        { id: 1075, english: 'Do it now', phonetic: 'Dú it náu', translation: 'Faça isso agora' },
        { id: 1076, english: 'Listen to this', phonetic: 'Lí-cen tu dhís', translation: 'Ouça isso' },
        { id: 1077, english: 'Watch your step', phonetic: 'Uátch iór istép', translation: 'Cuidado onde pisa' },
        { id: 1078, english: 'Call me back', phonetic: 'Cól mi béc', translation: 'Me ligue de volta' },
        { id: 1079, english: 'Give it back', phonetic: 'Guív it béc', translation: 'Devolva' },
        { id: 1080, english: 'I’m so proud', phonetic: 'Áim sôu práud', translation: 'Estou tão orgulhoso' },
        // Daily Questions
        { id: 1081, english: 'What happened?', phonetic: 'Uat ré-pênd?', translation: 'O que aconteceu?' },
        { id: 1082, english: 'Are you sure?', phonetic: 'Ár iú shúr?', translation: 'Você tem certeza?' },
        { id: 1083, english: 'Who is it?', phonetic: 'Rú is it?', translation: 'Quem é?' },
        { id: 1084, english: 'Is everything okay?', phonetic: 'Is é-vri-thing ôu-kêi?', translation: 'Está tudo bem?' },
        { id: 1085, english: 'What do you need?', phonetic: 'Uat dú iú níd?', translation: 'Do que você precisa?' },
        { id: 1086, english: 'Can you help me?', phonetic: 'Quen iú relp mi?', translation: 'Você pode me ajudar?' },
        { id: 1087, english: 'Where are we?', phonetic: 'Uér ár uí?', translation: 'Onde estamos?' },
        { id: 1088, english: 'When is it?', phonetic: 'Uên is it?', translation: 'Quando é?' },
        { id: 1089, english: 'Why not?', phonetic: 'Uái nót?', translation: 'Por que não?' },
        { id: 1090, english: 'How much is it?', phonetic: 'Rau mâtch is it?', translation: 'Quanto custa?' },
        // Small Talk
        { id: 1091, english: 'Nice weather today', phonetic: 'Náice ué-dhêr tu-dêi', translation: 'Tempo bom hoje' },
        { id: 1092, english: 'I love this place', phonetic: 'Ái lárv dhís plêice', translation: 'Eu amo este lugar' },
        { id: 1093, english: 'Are you from here?', phonetic: 'Ár iú fróm rí-êr?', translation: 'Você é daqui?' },
        { id: 1094, english: 'I am a tourist', phonetic: 'Ái ém ê tú-ríst', translation: 'Eu sou turista' },
        { id: 1095, english: 'I don’t speak much English', phonetic: 'Ái dôunt spíc mâtch ínglish', translation: 'Não falo muito inglês' },
        // Directions
        { id: 1096, english: 'Turn right', phonetic: 'Tãrn ráit', translation: 'Vire à direita' },
        { id: 1097, english: 'Turn left', phonetic: 'Tãrn léft', translation: 'Vire à esquerda' },
        { id: 1098, english: 'Go straight', phonetic: 'Góu istrêit', translation: 'Vá direto' },
        { id: 1099, english: 'It’s near here', phonetic: 'Its nír rí-êr', translation: 'É perto daqui' },
        { id: 1100, english: 'It’s far away', phonetic: 'Its fár a-uêi', translation: 'É longe' },
        // Time & Dates
        { id: 1101, english: 'What time is it?', phonetic: 'Uat táim is it?', translation: 'Que horas são?' },
        { id: 1102, english: 'It’s early', phonetic: 'Its ãr-li', translation: 'É cedo' },
        { id: 1103, english: 'It’s late', phonetic: 'Its lêit', translation: 'É tarde' },
        { id: 1104, english: 'Tomorrow morning', phonetic: 'Tu-mó-rou mór-ning', translation: 'Amanhã de manhã' },
        { id: 1105, english: 'Yesterday night', phonetic: 'Iés-têr-dêi náit', translation: 'Ontem à noite' },
        { id: 1106, english: 'Next week', phonetic: 'Nécst uíc', translation: 'Semana que vem' },
        { id: 1107, english: 'Last month', phonetic: 'Lést mánth', translation: 'Mês passado' },
        { id: 1108, english: 'Every day', phonetic: 'É-vri dêi', translation: 'Todo dia' },
        { id: 1109, english: 'Sometimes', phonetic: 'Sãm-táimz', translation: 'Às vezes' },
        { id: 1110, english: 'Never again', phonetic: 'Né-vêr a-guên', translation: 'Nunca mais' },
        // Social
        { id: 1111, english: 'Can you hear me?', phonetic: 'Quen iú rí-êr mi?', translation: 'Você consegue me ouvir?' },
        { id: 1112, english: 'I am joking', phonetic: 'Ái ém djôu-king', translation: 'Estou brincando' },
        { id: 1113, english: 'Don’t be serious', phonetic: 'Dôunt bí sí-ri-ús', translation: 'Não seja sério' },
        { id: 1114, english: 'It was fun', phonetic: 'It uós fãn', translation: 'Foi divertido' },
        { id: 1115, english: 'I enjoyed it', phonetic: 'Ái en-djóid it', translation: 'Eu gostei/aproveitei' },
    ],
    'Avançado': [
        { id: 2001, english: 'Could you help me find this address?', phonetic: 'Culd iú relp mi fáind dhís a-dréss?', translation: 'Pode me ajudar a achar este endereço?' },
        { id: 2002, english: 'I would like to make a reservation', phonetic: 'Ái uuld láic tu mêic ê re-zêr-vêi-shon', translation: 'Eu gostaria de fazer uma reserva' },
        { id: 2003, english: 'What time does the train leave?', phonetic: 'Uat táim dãs dâ trêin lív?', translation: 'Que horas o trem sai?' },
        { id: 2004, english: 'Is there a pharmacy open 24 hours?', phonetic: 'Is dhér ê fár-ma-ci ôupen tu-én-ti fór áu-êrs?', translation: 'Tem uma farmácia aberta 24 horas?' },
        { id: 2005, english: 'I am allergic to some medications', phonetic: 'Ái ém a-lér-djic tu sãm me-di-cêi-shons', translation: 'Sou alérgico a alguns remédios' },
        { id: 2006, english: 'Can you show me on the map?', phonetic: 'Quen iú shôu mi ón dâ mép?', translation: 'Pode me mostrar no mapa?' },
        { id: 2007, english: 'I need to go to the airport', phonetic: 'Ái níd tu góu tu dâ ér-pórt', translation: 'Eu preciso ir ao aeroporto' },
        { id: 2008, english: 'Where can I exchange my money?', phonetic: 'Uér quen ái équis-tshêndj mái mã-ni?', translation: 'Onde posso trocar meu dinheiro?' },
        { id: 2009, english: 'Which bus goes to the city center?', phonetic: 'Uítch bãs gôus tu dâ sí-ti sén-têr?', translation: 'Qual ônibus vai para o centro?' },
        { id: 2010, english: 'I would like to order a pizza', phonetic: 'Ái uuld láic tu ór-dêr ê pí-tzâ', translation: 'Eu gostaria de pedir uma pizza' },
        { id: 2011, english: 'Are you ready to order?', phonetic: 'Ár iú ré-di tu ór-dêr?', translation: 'Você está pronto para pedir?' },
        { id: 2012, english: 'What do you recommend to eat?', phonetic: 'Uat du iú re-co-ménd tu ít?', translation: 'O que você recomenda comer?' },
        { id: 2013, english: 'I want a room with a view', phonetic: 'Ái uónt ê rûm uíd ê viú', translation: 'Quero um quarto com vista' },
        { id: 2014, english: 'Is breakfast included in the price?', phonetic: 'Is bréc-fást in-clú-dêd in dâ práis?', translation: 'O café da manhã está incluso no preço?' },
        { id: 2015, english: 'The Wi-Fi is not working', phonetic: 'Dâ uái-fái is nót uãr-king', translation: 'O Wi-Fi não está funcionando' },
        { id: 2016, english: 'I would like to check out now', phonetic: 'Ái uuld láic tu tchéc áut náu', translation: 'Eu gostaria de fazer o check-out agora' },
        { id: 2017, english: 'Can I pay with a credit card?', phonetic: 'Quen ái pêi uíd ê créd-it cárd?', translation: 'Posso pagar com cartão de crédito?' },
        { id: 2018, english: 'I lost my keys and my wallet', phonetic: 'Ái lóst mái quís énd mái uó-let', translation: 'Perdi minhas chaves e minha carteira' },
        { id: 2019, english: 'Where is the nearest police station?', phonetic: 'Uér is dâ nír-ést po-lís istêi-shon?', translation: 'Onde é o posto policial mais próximo?' },
        { id: 2020, english: 'I need to call my family', phonetic: 'Ái níd tu cól mái fâ-mi-li', translation: 'Eu preciso ligar para minha família' },
        { id: 2021, english: 'Could you speak a bit slower?', phonetic: 'Culd iú spíc ê bít slôu-êr?', translation: 'Poderia falar um pouco mais devagar?' },
        { id: 2022, english: 'Do you speak Portuguese?', phonetic: 'Du iú spíc Pór-chu-guis?', translation: 'Você fala português?' },
        { id: 2023, english: 'How do I say this in English?', phonetic: 'Rau du ái sêi dhís in ínglish?', translation: 'Como se fala isso em inglês?' },
        { id: 2024, english: 'I am here for a business trip', phonetic: 'Ái ém rí-êr fór ê bíz-ness tríp', translation: 'Estou aqui em viagem de negócios' },
        { id: 2025, english: 'I am looking for a gift', phonetic: 'Ái ém lú-king fór ê guíft', translation: 'Estou procurando um presente' },
        { id: 2026, english: 'Is it far from here?', phonetic: 'Is it fár fróm rí-êr?', translation: 'Fica longe daqui?' },
        { id: 2027, english: 'I am enjoying my stay', phonetic: 'Ái ém en-djói-ing mái istêi', translation: 'Estou gostando da minha estadia' },
        { id: 2028, english: 'What is the weather like?', phonetic: 'Uat is dâ ué-dêr láic?', translation: 'Como está o tempo?' },
        { id: 2029, english: 'Can I have some water, please?', phonetic: 'Quen ái rév sãm uóter, plís?', translation: 'Pode me dar um pouco de água, por favor?' },
        { id: 2030, english: 'Nice to talk to you', phonetic: 'Náis tu tólc tu iú', translation: 'Bom conversar com você' },
        { id: 2031, english: 'I will be back tomorrow', phonetic: 'Ái uíl bi béc tu-mó-rou', translation: 'Eu voltarei amanhã' },
        { id: 2032, english: 'Where can I buy a ticket?', phonetic: 'Uér quen ái bái ê tí-quet?', translation: 'Onde posso comprar uma passagem?' },
        { id: 2033, english: 'I have a question', phonetic: 'Ái rév ê qués-tshon', translation: 'Eu tenho uma pergunta' },
        { id: 2034, english: 'What does this word mean?', phonetic: 'Uat dãs dhís uãrd mín?', translation: 'O que essa palavra significa?' },
        { id: 2035, english: 'I want to improve my English', phonetic: 'Ái uónt tu im-prûv mái ínglish', translation: 'Quero melhorar meu inglês' },
        { id: 2036, english: 'It is a pleasure to meet you', phonetic: 'It is ê plé-jure tu mít iú', translation: 'É um prazer conhecer você' },
        { id: 2037, english: 'I am waiting for a friend', phonetic: 'Ái ém uêi-ting fór ê frénd', translation: 'Estou esperando por um amigo' },
        { id: 2038, english: 'Do you have a menu?', phonetic: 'Du iú rév ê mé-niu?', translation: 'Você tem um cardápio?' },
        { id: 2039, english: 'I am very tired', phonetic: 'Ái ém vé-ri tái-êrd', translation: 'Estou muito cansado' },
        { id: 2040, english: 'Where is the entrance?', phonetic: 'Uér is dâ én-trance?', translation: 'Onde é a entrada?' },
        { id: 2041, english: 'Could you give me some advice?', phonetic: 'Culd iú guív mi sãm ad-váice?', translation: 'Poderia me dar um conselho?' },
        { id: 2042, english: 'I am really looking forward to it', phonetic: 'Ái ém rí-li lú-king fór-uãrd tu it', translation: 'Estou ansioso por isso' },
        { id: 2043, english: 'That makes a lot of sense', phonetic: 'Dhét mêics ê lót óv sénce', translation: 'Isso faz muito sentido' },
        { id: 2044, english: 'I am not quite sure I understand', phonetic: 'Ái ém nót quáit shú-êr ái andêrstend', translation: 'Não tenho certeza se entendi' },
        { id: 2045, english: 'Let me check my schedule', phonetic: 'Lét mi tchéc mái isquéd-jul', translation: 'Deixe-me checar minha agenda' },
        { id: 2046, english: 'How long does it take to get there?', phonetic: 'Rau lóng dãs it têic tu guét dhér?', translation: 'Quanto tempo leva para chegar lá?' },
        { id: 2047, english: 'Could you please call me a taxi?', phonetic: 'Culd iú plís cól mi ê té-csi?', translation: 'Poderia por favor me chamar um táxi?' },
        { id: 2048, english: 'What is the best way to learn?', phonetic: 'Uat is dâ bést uêi tu lãrn?', translation: 'Qual a melhor forma de aprender?' },
        { id: 2049, english: 'I would appreciate your help', phonetic: 'Ái uuld a-prí-sh-êit iór relp', translation: 'Eu agradeceria sua ajuda' },
        { id: 2050, english: 'It was a long day at work', phonetic: 'It uós ê lóng dêi ét uãrk', translation: 'Foi um dia longo no trabalho' },
        { id: 2051, english: 'I am looking for a new opportunity', phonetic: 'Ái ém lú-king fór ê niú ó-pôr-tu-ní-ti', translation: 'Estou procurando uma nova oportunidade' },
        { id: 2052, english: 'What are the next steps?', phonetic: 'Uat ár dâ nécsit istéps?', translation: 'Quais são os próximos passos?' },
        { id: 2053, english: 'I will do my best', phonetic: 'Ái uíl dú mái bést', translation: 'Eu farei o meu melhor' },
        { id: 2054, english: 'Thanks for your patience', phonetic: 'Téncs fór iór pêi-shense', translation: 'Obrigado pela sua paciência' },
        { id: 2055, english: 'I will let you know', phonetic: 'Ái uíl lét iú nôu', translation: 'Eu te aviso' },
        { id: 2056, english: 'That is exactly what I thought', phonetic: 'Dhét is é-gsé-tli uat ái tót', translation: 'Foi exatamente o que eu pensei' },
        { id: 2057, english: 'Should we start now?', phonetic: 'Shuld uí istárt náu?', translation: 'Devemos começar agora?' },
        { id: 2058, english: 'I am here to support you', phonetic: 'Ái ém rí-êr tu sã-pórt iú', translation: 'Estou aqui para te apoiar' },
        { id: 2059, english: 'It’s been a pleasure working with you', phonetic: 'Its bín ê plé-jure uãr-king uíd iú', translation: 'Tem sido um prazer trabalhar com você' },
        { id: 2060, english: 'Where can I find more information?', phonetic: 'Uér quen ái fáind mór in-fôr-mêi-shon?', translation: 'Onde posso encontrar mais informações?' },
        { id: 2061, english: 'I apologize for the delay', phonetic: 'Ái a-pó-lo-djáize fór dâ di-lêi', translation: 'Peço desculpas pelo atraso' },
        { id: 2062, english: 'Let’s keep in touch', phonetic: 'Léts quíp in tãtch', translation: 'Vamos manter contato' },
        { id: 2063, english: 'It was worth it', phonetic: 'It uós uãr-th it', translation: 'Valeu a pena' },
        { id: 2064, english: 'I am not used to this', phonetic: 'Ái ém nót iú-zd tu dhís', translation: 'Não estou acostumado com isso' },
        { id: 2065, english: 'What’s the point of this?', phonetic: 'Uats dâ póint óv dhís?', translation: 'Qual é o sentido disso?' },
        { id: 2066, english: 'Can you believe it?', phonetic: 'Quen iú bi-lí-v it?', translation: 'Você consegue acreditar?' },
        { id: 2067, english: 'I didn’t expect that', phonetic: 'Ái dí-dent é-csi-péct dhét', translation: 'Eu não esperava por essa' },
        { id: 2068, english: 'That’s a great idea', phonetic: 'Dhéts ê grêit ái-dí-a', translation: 'Essa é uma ótima ideia' },
        { id: 2069, english: 'I’m very excited about it', phonetic: 'Áim vé-ri é-csái-têd a-báut it', translation: 'Estou muito animado com isso' },
        { id: 2070, english: 'Don’t take it personally', phonetic: 'Dôunt têic it pãr-so-na-li', translation: 'Não leve para o lado pessoal' },
        { id: 2071, english: 'It’s none of my business', phonetic: 'Its nãn óv mái bíz-ness', translation: 'Não é da minha conta' },
        { id: 2072, english: 'I have mixed feelings', phonetic: 'Ái rév mí-csid fí-língs', translation: 'Tenho sentimentos mistos' },
        { id: 2073, english: 'Let’s get down to business', phonetic: 'Léts guét dáun tu bíz-ness', translation: 'Vamos direto ao assunto' },
        { id: 2074, english: 'I’ll take care of it', phonetic: 'Áil têic quér óv it', translation: 'Eu cuido disso' },
        { id: 2075, english: 'It’s up to you', phonetic: 'Its ãp tu iú', translation: 'Depende de você' },
        { id: 2076, english: 'Better late than never', phonetic: 'Bé-têr lêit dhén né-vêr', translation: 'Antes tarde do que nunca' },
        { id: 2077, english: 'I’m running out of time', phonetic: 'Áim rã-ning áut óv táim', translation: 'Estou ficando sem tempo' },
        { id: 2078, english: 'That’s out of the question', phonetic: 'Dhéts áut óv dâ qués-tshon', translation: 'Isso está fora de questão' },
        { id: 2079, english: 'It’s a piece of cake', phonetic: 'Its ê píce óv quêic', translation: 'É moleza (pedaço de bolo)' },
        { id: 2080, english: 'I’m feeling under the weather', phonetic: 'Áim fí-ling ãn-dêr dâ ué-dhêr', translation: 'Não estou me sentindo bem' },
        // Professional/Work
        { id: 2081, english: 'Could you please repeat that?', phonetic: 'Culd iú plíze ri-pít dhét?', translation: 'Pode repetir por favor?' },
        { id: 2082, english: 'I didn’t catch your name', phonetic: 'Ái dí-dent quétch iór nêim', translation: 'Não peguei seu nome' },
        { id: 2083, english: 'Let’s schedule a meeting', phonetic: 'Léts i-squé-djul ê mí-ting', translation: 'Vamos agendar uma reunião' },
        { id: 2084, english: 'I need to check my calendar', phonetic: 'Ái níd tu tchéc mái cá-len-dãr', translation: 'Preciso checar minha agenda' },
        { id: 2085, english: 'Thank you for the opportunity', phonetic: 'Ténc iú fór dâ ó-pôr-tu-ní-ti', translation: 'Obrigado pela oportunidade' },
        // Travel/International
        { id: 2086, english: 'I have a flight to catch', phonetic: 'Ái rév ê fláit tu quétch', translation: 'Tenho um voo para pegar' },
        { id: 2087, english: 'Where is the departures gate?', phonetic: 'Uér is dâ di-pár-tshurz guêit?', translation: 'Onde é o portão de embarque?' },
        { id: 2088, english: 'I’d like to see the menu, please', phonetic: 'Áid láic tu sí dâ mé-niu plíze', translation: 'Eu gostaria de ver o cardápio, por favor' },
        { id: 2089, english: 'Is service included?', phonetic: 'Is sãr-vi-ce in-clú-dêd?', translation: 'O serviço está incluso?' },
        { id: 2090, english: 'I need a taxi to the airport', phonetic: 'Ái níd ê té-csi tu dâ ér-pórt', translation: 'Preciso de um táxi para o aeroporto' },
        // Emergencies
        { id: 2091, english: 'I lost my passport', phonetic: 'Ái lórst mái pás-pórt', translation: 'Perdi meu passaporte' },
        { id: 2092, english: 'I need to see a doctor', phonetic: 'Ái níd tu sí ê dóc-tôr', translation: 'Preciso ver um médico' },
        { id: 2093, english: 'Where is the nearest pharmacy?', phonetic: 'Uér is dâ nír-êst fár-ma-ci?', translation: 'Onde é a farmácia mais próxima?' },
        { id: 2094, english: 'My phone was stolen', phonetic: 'Mái fôun uós is-tôu-lên', translation: 'Meu celular foi roubado' },
        { id: 2095, english: 'I am lost, can you guide me?', phonetic: 'Ái ém lórst, quen iú gái-di mi?', translation: 'Estou perdido, pode me guiar?' },
    ]
};

export const categoriesMap = {
    'Básico': 'Básico (Palavras)',
    'Médio': 'Médio (Frases Curtas)',
    'Avançado': 'Avançado (Frases Longas)',
    'Conversar': '🤖 Conversar (IA)'
};
